"""
config/schema.py — JSON Schema generation, export, and YAML-against-schema validation.

This module serves three purposes:

1. **Schema generation** — derives JSON Schema from Pydantic v2 models so that
   external tools (IDE YAML plugins, pre-commit hooks, CI validators) can
   validate configs without importing the full Python package.

2. **Schema export** — writes ``configs/agent-config.schema.json`` and
   ``configs/scheduler.schema.json`` on demand (or from CI).

3. **Runtime YAML validation** — validates a YAML dict against the schema before
   handing it to Pydantic, giving clearer error messages for simple mistakes.

Traces: SRC-071 (fail loudly with clear errors), SRC-072 (per-agent YAML schemas),
        SRC-073 (schema must forbid secrets fields)

CLI usage::

    python -m ai_news_agent.config.schema --export-dir configs/
    python -m ai_news_agent.config.schema --validate configs/default-agent.yaml
    python -m ai_news_agent.config.schema --validate configs/scheduler.yaml --type scheduler
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

from ai_news_agent.config.models import AgentConfig, SchedulerConfig

# ---------------------------------------------------------------------------
# Schema generation
# ---------------------------------------------------------------------------


def generate_agent_schema() -> dict[str, Any]:
    """
    Generate a JSON Schema dict from the :class:`AgentConfig` Pydantic model.

    The schema is generated by Pydantic v2's ``model_json_schema()`` and
    then enriched with:
    - A ``$schema`` declaration (Draft 7).
    - A ``title`` and ``description`` block documenting the schema's purpose.
    - A ``$comment`` pointing to the implementation plan for traceability.

    Traces: SRC-071–SRC-073 (config validation contract)

    Returns:
        A JSON-serialisable dict representing the full JSON Schema.
    """
    raw_schema = AgentConfig.model_json_schema()

    # Enrich with metadata
    raw_schema.setdefault("$schema", "http://json-schema.org/draft-07/schema#")
    raw_schema["title"] = "AI News Agent — Per-Agent Configuration Schema"
    raw_schema["description"] = (
        "JSON Schema for a per-agent YAML configuration file. "
        "Validated by load_agent_config() at startup. "
        "Secrets (API keys, tokens) must NEVER appear in this file — use env vars. "
        "Requirement traces: SRC-017–SRC-021, SRC-029–SRC-032, SRC-036–SRC-046, "
        "SRC-054, SRC-057, SRC-071–SRC-073, SRC-113, SRC-129, SRC-145."
    )
    raw_schema["$comment"] = (
        "Generated from ai_news_agent.config.models.AgentConfig. "
        "See docs/requirements/implementation-plan.md (SLICE-003) for traceability. "
        "Do not edit manually — regenerate with: "
        "python -m ai_news_agent.config.schema --export-dir configs/"
    )

    return raw_schema


def generate_scheduler_schema() -> dict[str, Any]:
    """
    Generate a JSON Schema dict from the :class:`SchedulerConfig` Pydantic model.

    Traces: SRC-052, SRC-072, SRC-144, SRC-147

    Returns:
        A JSON-serialisable dict representing the full JSON Schema.
    """
    raw_schema = SchedulerConfig.model_json_schema()

    raw_schema.setdefault("$schema", "http://json-schema.org/draft-07/schema#")
    raw_schema["title"] = "AI News Agent — Scheduler Configuration Schema"
    raw_schema["description"] = (
        "JSON Schema for configs/scheduler.yaml. "
        "Defines retry policy, cron triggers, API settings, and agent registry. "
        "Requirement traces: SRC-052, SRC-072, SRC-144, SRC-147."
    )
    raw_schema["$comment"] = (
        "Generated from ai_news_agent.config.models.SchedulerConfig. "
        "Regenerate with: python -m ai_news_agent.config.schema --export-dir configs/"
    )

    return raw_schema


# ---------------------------------------------------------------------------
# Schema export
# ---------------------------------------------------------------------------


def export_schemas(export_dir: str | Path = "configs") -> None:
    """
    Write JSON Schema files to ``export_dir``.

    Files written:
    - ``{export_dir}/agent-config.schema.json``
    - ``{export_dir}/scheduler.schema.json``

    These files are designed to be checked in alongside YAML configs so that
    IDE plugins (e.g. VS Code YAML extension with ``yaml.schemas`` setting)
    can provide inline validation and autocompletion.

    Traces: SRC-071 (schema enables fast early validation)

    Args:
        export_dir: Directory where schema files will be written.
                    Created if it does not exist.
    """
    out_dir = Path(export_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    agent_path = out_dir / "agent-config.schema.json"
    scheduler_path = out_dir / "scheduler.schema.json"

    agent_schema = generate_agent_schema()
    scheduler_schema = generate_scheduler_schema()

    agent_path.write_text(
        json.dumps(agent_schema, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    scheduler_path.write_text(
        json.dumps(scheduler_schema, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )

    print(f"✓ Wrote agent schema  → {agent_path}")
    print(f"✓ Wrote scheduler schema → {scheduler_path}")


# ---------------------------------------------------------------------------
# Runtime validation helpers
# ---------------------------------------------------------------------------


class SchemaValidationError(Exception):
    """
    Raised when a YAML document fails JSON Schema or Pydantic validation.
    Contains structured error details for display to the user.

    Traces: SRC-071 (fail loudly with actionable messages)
    """

    def __init__(self, errors: list[str], source: str = "<unknown>") -> None:
        self.errors = errors
        self.source = source
        super().__init__(
            f"Configuration validation failed for {source}:\n"
            + "\n".join(f"  • {e}" for e in errors)
        )


def validate_agent_yaml(
    path: str | Path,
    *,
    strict: bool = False,
) -> AgentConfig:
    """
    Fully validate an agent YAML file and return the parsed :class:`AgentConfig`.

    Performs:
    1. YAML parse check.
    2. Pydantic schema validation (produces typed AgentConfig).
    3. Optionally: ``strict=True`` raises on any extra fields.

    This function is primarily for the CLI validator and pre-commit hooks.
    Production code should use :func:`ai_news_agent.config.loader.load_agent_config`.

    Args:
        path:   Path to the agent YAML file.
        strict: If True, raise on extra/unrecognised fields in the YAML.

    Returns:
        Validated :class:`AgentConfig`.

    Raises:
        :class:`SchemaValidationError`: On any validation failure.
    """
    from ai_news_agent.config.loader import ConfigError, validate_no_secrets_in_yaml

    resolved = Path(path)
    errors: list[str] = []

    if not resolved.exists():
        raise SchemaValidationError(
            [f"File not found: {resolved.absolute()}"], source=str(resolved)
        )

    raw_text = resolved.read_text(encoding="utf-8")

    # Secret scan (SRC-073)
    try:
        validate_no_secrets_in_yaml(raw_text, source_name=str(resolved))
    except ConfigError as exc:
        errors.append(str(exc))

    # YAML parse
    try:
        data = yaml.safe_load(raw_text) or {}
    except yaml.YAMLError as exc:
        raise SchemaValidationError([f"YAML parse error: {exc}"], source=str(resolved)) from exc

    # Pydantic validation
    from pydantic import ValidationError

    try:
        config = AgentConfig.model_validate(data)
    except ValidationError as exc:
        for error in exc.errors():
            loc = " → ".join(str(p) for p in error["loc"])
            errors.append(f"[{loc}] {error['msg']}")

    if errors:
        raise SchemaValidationError(errors, source=str(resolved))

    return config  # type: ignore[return-value]


def validate_scheduler_yaml(path: str | Path) -> SchedulerConfig:
    """
    Fully validate a scheduler YAML file and return the parsed :class:`SchedulerConfig`.

    Args:
        path: Path to scheduler.yaml.

    Returns:
        Validated :class:`SchedulerConfig`.

    Raises:
        :class:`SchemaValidationError`: On any validation failure.

    Traces: SRC-052, SRC-072
    """
    from ai_news_agent.config.loader import ConfigError, validate_no_secrets_in_yaml

    resolved = Path(path)
    errors: list[str] = []

    if not resolved.exists():
        raise SchemaValidationError(
            [f"File not found: {resolved.absolute()}"], source=str(resolved)
        )

    raw_text = resolved.read_text(encoding="utf-8")

    try:
        validate_no_secrets_in_yaml(raw_text, source_name=str(resolved))
    except ConfigError as exc:
        errors.append(str(exc))

    try:
        data = yaml.safe_load(raw_text) or {}
    except yaml.YAMLError as exc:
        raise SchemaValidationError([f"YAML parse error: {exc}"], source=str(resolved)) from exc

    from pydantic import ValidationError

    try:
        config = SchedulerConfig.model_validate(data)
    except ValidationError as exc:
        for error in exc.errors():
            loc = " → ".join(str(p) for p in error["loc"])
            errors.append(f"[{loc}] {error['msg']}")

    if errors:
        raise SchemaValidationError(errors, source=str(resolved))

    return config  # type: ignore[return-value]


def summarise_agent_config(config: AgentConfig) -> str:
    """
    Return a human-readable summary of a validated agent config.

    Used by the CLI validator to confirm what was parsed.

    Traces: SRC-072 (config visibility)
    """
    cadence_overrides = (
        ", ".join(f"{k}={v.model}" for k, v in config.llm.cadence_overrides.items()) or "none"
    )
    handle_list = (
        ", ".join(f"@{h.handle}(×{h.weight})" for h in config.twitter.handles[:5])
        or "none configured"
    )
    if len(config.twitter.handles) > 5:
        handle_list += f" … +{len(config.twitter.handles) - 5} more"

    tier_counts = {
        "1a (custom)": len(config.sources.custom),
        "1b (business press)": len(config.sources.tier_1b),
        "2 (AI blogs)": len(config.sources.tier_2),
        "3 (tech press)": len(config.sources.tier_3),
        "4 (policy/research)": len(config.sources.tier_4),
    }
    tiers_str = ", ".join(
        f"Tier {tier}: {count}" for tier, count in tier_counts.items() if count > 0
    )

    return (
        f"\n{'─' * 60}\n"
        f"  Agent ID   : {config.agent_id}\n"
        f"  LLM        : {config.llm.provider} / {config.llm.model}\n"
        f"  Overrides  : {cadence_overrides}\n"
        f"  Prompt dir : {config.curation_prompt}\n"
        f"  Output dir : {config.output_dir}\n"
        f"  Limits     : daily={config.limits.daily_top_n}, "
        f"weekly={config.limits.weekly_top_n}, "
        f"monthly={config.limits.monthly_top_n}, "
        f"annual={config.limits.annual_top_n}\n"
        f"  Sources    : {tiers_str or 'none configured'}\n"
        f"  Twitter    : {'enabled' if config.twitter.enabled else 'disabled'} — {handle_list}\n"
        f"{'─' * 60}\n"
    )


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def _cli_main(argv: list[str] | None = None) -> int:
    """
    CLI validator and schema exporter.

    Commands::

        # Export JSON Schema files to configs/
        python -m ai_news_agent.config.schema --export-dir configs/

        # Validate a specific agent YAML
        python -m ai_news_agent.config.schema --validate configs/default-agent.yaml

        # Validate the scheduler YAML
        python -m ai_news_agent.config.schema --validate configs/scheduler.yaml --type scheduler

        # Validate and show config summary
        python -m ai_news_agent.config.schema --validate configs/default-agent.yaml --summary

    Exit codes: 0 = success, 1 = validation failure, 2 = argument error.

    Traces: SRC-071 (clear error output), SRC-072 (multi-config support)
    """
    parser = argparse.ArgumentParser(
        prog="ai_news_agent.config.schema",
        description=(
            "AI News Agent config validator and JSON Schema exporter.\n\n"
            "Examples:\n"
            "  python -m ai_news_agent.config.schema --export-dir configs/\n"
            "  python -m ai_news_agent.config.schema --validate configs/default-agent.yaml\n"
            "  python -m ai_news_agent.config.schema --validate configs/scheduler.yaml "
            "--type scheduler"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--export-dir",
        metavar="DIR",
        help=(
            "Export JSON Schema files to DIR. "
            "Writes agent-config.schema.json and scheduler.schema.json."
        ),
    )
    mode.add_argument(
        "--validate",
        metavar="PATH",
        nargs="+",
        help="One or more YAML config files to validate.",
    )

    parser.add_argument(
        "--type",
        choices=["agent", "scheduler"],
        default="agent",
        help="Config type when using --validate (default: agent).",
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Print a human-readable summary of the validated config.",
    )
    parser.add_argument(
        "--json-schema",
        action="store_true",
        help=("When used with --validate, also print the JSON Schema to stdout for reference."),
    )

    args = parser.parse_args(argv)

    # ── Export mode ──────────────────────────────────────────────────────────
    if args.export_dir:
        export_schemas(args.export_dir)
        return 0

    # ── Validate mode ─────────────────────────────────────────────────────────
    paths = [Path(p) for p in args.validate]
    config_type = args.type

    if args.json_schema:
        schema = generate_agent_schema() if config_type == "agent" else generate_scheduler_schema()
        print(json.dumps(schema, indent=2))
        print()

    exit_code = 0
    for path in paths:
        try:
            if config_type == "agent":
                config = validate_agent_yaml(path)
                print(f"✓ {path} — valid agent configuration")
                if args.summary:
                    print(summarise_agent_config(config))
            else:
                sched = validate_scheduler_yaml(path)
                enabled = sum(1 for a in sched.agents if a.enabled)
                print(
                    f"✓ {path} — valid scheduler configuration "
                    f"({len(sched.agents)} agents registered, {enabled} enabled)"
                )
                if args.summary:
                    print(f"  Agents: {', '.join(a.id for a in sched.agents)}")
                    print(f"  Retries: {sched.scheduler.max_retries}")
                    print(f"  Backoff: {sched.scheduler.retry_backoff_base_seconds}s base")

        except SchemaValidationError as exc:
            print(f"✗ Validation FAILED for {path}:", file=sys.stderr)
            for error in exc.errors:
                print(f"  • {error}", file=sys.stderr)
            exit_code = 1

    return exit_code


if __name__ == "__main__":
    sys.exit(_cli_main())
